import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import React, { Suspense } from "react";

export const metadata: Metadata = {
  title: "Snoopy Airlines",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-blue-300 via-sky-200 to-yellow-100">
        <Suspense fallback={<div>Loading...</div>}>
          <Navbar />
          {children}
        </Suspense>
      </body>
    </html>
  );
}
